"""create uploads and units tables

Revision ID: 4bf631a2e819
Revises: 
Create Date: 2026-04-20 01:52:16.252162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf631a2e819'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('developer_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('price_total', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('finishing_status', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor_number', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_area_m2'), 'units', ['area_m2'], unique=False)
    op.create_index(op.f('ix_units_bedrooms'), 'units', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_units_developer_name'), 'units', ['developer_name'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_location'), 'units', ['location'], unique=False)
    op.create_index(op.f('ix_units_price_total'), 'units', ['price_total'], unique=False)
    op.create_index(op.f('ix_units_project_name'), 'units', ['project_name'], unique=False)
    op.create_index(op.f('ix_units_stage'), 'units', ['stage'], unique=False)
    op.create_index(op.f('ix_units_unit_type'), 'units', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_type'), table_name='units')
    op.drop_index(op.f('ix_units_stage'), table_name='units')
    op.drop_index(op.f('ix_units_project_name'), table_name='units')
    op.drop_index(op.f('ix_units_price_total'), table_name='units')
    op.drop_index(op.f('ix_units_location'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_developer_name'), table_name='units')
    op.drop_index(op.f('ix_units_bedrooms'), table_name='units')
    op.drop_index(op.f('ix_units_area_m2'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
